config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "books#index"

  resources :books do
    resources :rents, only: :create


    collection do
      get :my_titles
    end

    member do
      get :edit
    end

  end
  resources :rents, only: [:index, :destroy]
  get '/books', to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :rents, dependent: :destroy
  validates :title, :author_name, :published_year, :genre, :description, :price, presence: true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :address, presence: true
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!,only:[:index, :show]
  def index
    @rent = Rent.new
    if params[:genre].present?
      @books = Book.where(genre: params[:genre])
    else
      @books = Book.all
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to books_path, notice: 'Livro adicionado com sucesso'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def my_titles
    @books = Book.where(user: current_user)
  end

  def show
    @book = Book.find(params[:id])
    @rent = Rent.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to my_titles_books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
   redirect_to my_titles_books_path, notice: 'Livro atualizado com sucesso'
   else
   render :edit, status: :unprocessable_entity
   end

  end


  private

  def book_params
    params.require(:book).permit(:title, :author_name, :published_year, :genre, :description, :image, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @rent = Rent.new
    @rent.user = current_user
    @rent.book = @book
    @rent.save
    redirect_to rents_path
  end

  def index
    @rents = Rent.where(user: current_user)
  end

  def destroy
    @rent = Rent.find(params[:id])
    @rent.destroy
    redirect_to rents_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/edit.html.erb
<div class="container">

  <div class="text-center mt-3">
    <h1>Editar</h1>
  </div>

  <%= simple_form_for(@book) do |form| %>

    <div class="row justify-content-center">
        <div class="col-md-4 text-center" data-controller='preview'>
          <%= form.input :image, input_html: {data: {action: 'input->preview#img'}} %>
          <div data-preview-target='image'>
        </div>
    </div>

    <div class="col-md-5">
      <%= form.input :title, label: "Título" %>
      <%= form.input :author_name, label: "Autor"  %>
      <%= form.input :genre, label: "Gênero" %>
      <%= form.input :published_year, label: "Ano de publicação" %>
      <%= form.input :description, label: "Descrição" %>
      <%= form.input :price, label: "Preço da diária" %>
      <%= form.submit "Salvar", class: 'btn btn-primary col-3' %>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Bookshare</title>
   <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://sunrise.ng/wp-content/uploads/2021/02/Book-Giving-Day.jpg)">
    Bem-vindo ao Bookshare
  </div>
    <div class="row">
      <div class="col-2">
        <div class="genres side-menu">
            Gêneros
        </div>
        <ul class="genre-list side-menu">
          <li><%= link_to "Ficção", books_path(genre: "Ficção") %></li>
          <li><%= link_to "Romance", books_path(genre: "Romance") %></li>
          <li><%= link_to "Biografia", books_path(genre: "Biografia") %></li>
          <li><%= link_to "Autoajuda", books_path(genre: "Autoajuda") %></li>
          <li><%= link_to "Suspense", books_path(genre: "Suspense") %></li>
        </ul>
        <a class="btn btn-lg btn-info btn-side-menu" href="/books/my_titles">Meus Títulos</a>
      </div>
      <div class="book-suggestion col-9">
        <% @books.each do |book| %>
          <%= link_to book_path(book) do %>
            <div class="book-box" onclick="selectBook('O Livreiro de Cabul')">
              <div class="border book-card">
                <% if book.image.nil? %>
                  <%= image_tag 'https://cdn-icons-png.flaticon.com/512/2232/2232688.png', width: "300px", height: "220px" %>
                <% else  %>
                  <%= image_tag book.image, width: "300px", height: "220px" %>
                <% end %>
                <div class="book-title"><%= book.title.truncate(22) %></div>
                <div class="book-author"><%= book.author_name %></div>
                <div class="book-genre"><%= book.genre %></div>
                <div class="book-price">R$<%= book.price %></div>
                <% if book.rents.count.zero? %>
                  <%= simple_form_for [book, @rent] do |f| %>
                    <%= f.submit "Quero alugar", class: "btn btn-dark" %>
                  <% end %>
                <% else %>
                  <h4><span class="badge rounded-pill text-bg-danger badge-lg">Título indisponível</span></h4>
                <% end %>

              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

app/views/books/my_titles.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://sunrise.ng/wp-content/uploads/2021/02/Book-Giving-Day.jpg)">
  My Titles
</div>
<div class="container">

  <div class="row justify-content-around">
    <% if @books.count.zero? %>
      <h2>Nenhum livro disponível</h2>
    <% end %>

    <% @books.each do |book| %>

      <div class="card-product mt-3 col-5">
        <%= image_tag book.image %>
          <div class="card-product-infos">
          <h3><%= link_to book.title, book_path(book), class: "text-decoration-none link-dark" %></h3>
          <p>Author: <%= book.author_name %></p>
          <div class="d-flex">
            <%= link_to  "Edit", edit_book_path(book), class: "btn btn-sm btn-dark me-2" %>
            <%= button_to  "Delete", book_path(book), method: :delete, class: "btn btn-sm btn-dark me-2", data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          </div>
          </div>
      </div>
      <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="container">

  <div class="text-center mt-3">
    <h1>Disponibilizar para locação</h1>
  </div>

  <%= simple_form_for(@book) do |form| %>

  <div class="row justify-content-center">
    <div class="col-md-4 text-center" data-controller='preview'>
      <%= form.input :image, input_html: {data: {action: 'input->preview#img'}} %>
      <div data-preview-target='image'>
      </div>
    </div>

    <div class="col-md-5">
      <%= form.input :title, label: "Título" %>
      <%= form.input :author_name, label: "Autor"  %>

      <div class="flex-box">
      <%= form.input :genre, label: "Gênero", collection: %w[Ficção Romance Autoajuda Biografia Suspense] %>
      <%= form.input :published_year, label: "Ano de publicação" %>
      </div>

      <%= form.input :description, label: "Descrição" %>
      <%= form.input :price, label: "Preço da diária" %>


      <%= form.submit "Salvar", class: 'btn btn-dark col-3' %>

    </div>

  <% end %>
</div>

app/views/books/show.html.erb
<div class="container mt-5">
  <div class="row">


    <div class="col-3">
    <% if @book.image.nil? %>
        <%= image_tag 'https://cdn-icons-png.flaticon.com/512/2232/2232688.png' %>
        <% else  %>
        <%= image_tag @book.image %>
        <% end %>
    </div>


    <div class="card-book col-8">
      <div class="card-book-infos">
      <h3>Book: <%= @book.title %></h3>
      <p><strong>Author Name:</strong> <%= @book.author_name %></p>
      <p><strong>Description:</strong> <%= @book.description %></p>
      <p><strong>Published Year:</strong> <%= @book.published_year %></p>
      <p><strong>Genre:</strong> <%= @book.genre %></p>

      <% if @book.rents.count.zero? %>
        <%= simple_form_for [@book, @rent] do |f| %>
          <%= f.submit "Quero aluguar", class: "btn btn-dark" %>
        <% end %>
      <% else %>
        <span class="badge rounded-pill text-bg-danger">Título indisponível</span>
      <% end %>
    </div>
    </div>
  </div>

  <div class="mt-3">
  <h3>Price: <%= @book.price %> </h3>
  </div>



    <div class="card-product-infos">
    <h4>User Info</h4>
    <p><strong>Name:</strong> <%= @book.user.name %></p>
    <p><strong>Address:</strong> <%= @book.user.address %></p>
    </div>



<%= link_to "Back to home", books_path, class: "btn btn-dark" %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookshare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rents/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://sunrise.ng/wp-content/uploads/2021/02/Book-Giving-Day.jpg)">
  My Rents
</div>
<div class="container">
  <div class="mt-3">
      <div class="row justify-content-around">
          <% if @rents.count.zero? %>
            <h3>Nenhum livro alugado</h3>
          <% end %>


      <% @rents.each do |rent| %>
        <div class="card-product mt-3 col-5 ml-5">
          <% if rent.book.image.nil? %>
            <%= image_tag 'https://cdn-icons-png.flaticon.com/512/2232/2232688.png', width: "300px" %>
          <% else  %>
          <%= image_tag rent.book.image %>

          <% end %>
            <div class="card-product-infos">
              <h4><%= rent.book.title %></h4>
                <%= button_to "Devolver livro", rent_path(rent), method: :delete, data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}  %>
            </div>
        </div>
      <% end %>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to books_path, class: "navbar-brand" do %>
      <%= image_tag "https://cdn-icons-png.flaticon.com/512/167/167756.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My titles available", my_titles_books_path , class: "dropdown-item" %>
              <%= link_to "My rents", rents_path , class: "dropdown-item" %>
              <%= link_to "Create book", new_book_path, class: "dropdown-item" %>
              <%= link_to "Edit user", edit_user_registration_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>